#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"

export PATH=/usr/local/bin:/usr/local/sbin:$PATH:/Users/Aroq/bin

function take() {
  mkdir -p $1
  cd $1
}

source "$HOME/.console/console.rc" 2>/dev/null

export PATH=$PATH:/usr/local/m-cli

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export POWERLINE_CONFIG_COMMAND=/usr/local/bin/powerline-config

#tmux source "/usr/local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf"

# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/Aroq/bin/google-cloud-sdk/path.zsh.inc ]; then
  source '/Users/Aroq/bin/google-cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/Aroq/bin/google-cloud-sdk/completion.zsh.inc ]; then
  source '/Users/Aroq/bin/google-cloud-sdk/completion.zsh.inc'
fi

# export GOPATH=$HOME/.go
# export GOROOT=/usr/local/opt/go/libexec
# export PATH=$PATH:$GOROOT/bin:$GOPATH/bin


##Generated code START
export GOPATH=$HOME/Go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
##Generated code END
